// <auto-generated />
namespace VdoValley.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PostModelModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostModelModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201506141213578_PostModelModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
