// <auto-generated />
namespace VdoValley.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PersonnId_PersonId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonnId_PersonId));
        
        string IMigrationMetadata.Id
        {
            get { return "201507161634537_PersonnId_PersonId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
