// <auto-generated />
namespace VdoValley.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ratingg_Rating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ratingg_Rating));
        
        string IMigrationMetadata.Id
        {
            get { return "201507161542528_Ratingg_Rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
